title: OpenControl
remote_theme: 18F/uswds-jekyll
collections:
  pages:
    output: true
    permalink: /:name/
defaults:
  - scope:
      path: "_pages"
    values:
      layout: "page"
google_analytics_ua: UA-141012673-1
