site_name: OpenControl
repo_url: https://github.com/opencontrol/opencontrol-website/
google_analytics: ['UA-69554101-1', 'opencontrol.github.io']
remote_branch: master
pages:
  - Intro: 'index.md'
  - Members: 'members.md'
  - Event: 'event2016.md'
docs_dir: "docs"
